"""initial migration

Revision ID: 6b4f27c5230b
Revises: 
Create Date: 2026-08-29 19:41:19.553229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b4f27c5230b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='users_api'
    )
    op.create_index(op.f('ix_users_api_users_username'), 'users', ['username'], unique=True, schema='users_api')
    op.create_table('user_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_api.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='users_api'
    )
    op.create_index(op.f('ix_users_api_user_credentials_user_id'), 'user_credentials', ['user_id'], unique=True, schema='users_api')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_api_user_credentials_user_id'), table_name='user_credentials', schema='users_api')
    op.drop_table('user_credentials', schema='users_api')
    op.drop_index(op.f('ix_users_api_users_username'), table_name='users', schema='users_api')
    op.drop_table('users', schema='users_api')
    # ### end Alembic commands ###
